spring:
  application:
    name: v30
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://220.230.125.122/preorder?characterEncoding=utf-8
    username: preorder_user
    password: pre4r5t6y
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  mobile:
    devicedelegatingviewresolver:
      enabled: true
      tablet-prefix: /mobile
      mobile-prefix: /mobile
logging:
  config: classpath:logback-local.xml
g6:
  sms:
    test: false
log:
  slack:
    enabled: false
    webHookUrl: https://hooks.slack.com/services/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
    channel: g6
  database:
    enabled: false
  level: ERROR
v30:
  event-url: //lgupluslte2.diocean.co.kr/v30/main.asp
  event-url-mobile: //lgupluslte2.diocean.co.kr/v30/m/main.asp
  event-redirect: false
    
---

spring:
  profiles: development
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://220.230.125.122/preorder?characterEncoding=utf-8
    username: preorder_user
    password: pre4r5t6y
    tomcat:
      initial-size: 10
      max-active: 20
      min-idle: 10
      max-idle: 10
      max-wait: 3000
  thymeleaf:
    cache: true
    prefix: classpath:/templates
logging:
  config: classpath:logback-development.xml
server:
  port: 80
log:
  slack:
    enabled: false
  database:
    enabled: true    
    
---

spring:
  profiles: production
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.33.6.154/preorder?characterEncoding=utf-8
    username: preorder_user
    password: pre4r5t6y
    tomcat:
      initial-size: 10
      max-active: 20
      min-idle: 10
      max-idle: 10
      max-wait: 3000
  thymeleaf:
    cache: true
    prefix: classpath:/templates
logging:
  config: classpath:logback-production.xml
log:
  slack:
    enabled: true
  database:
    enabled: false   
v30:
  event-url: //event1.upluslte.co.kr/v30/main.asp
  event-url-mobile: //event1.upluslte.co.kr/v30/m/main.asp
  event-redirect: false